In [2]:
import numpy as np
matrix = np.random.randint(1, 101, size=(5, 5)) 
print("Original Matrix:")
print(matrix) 

Original Matrix:
[[70 95 93 41 68]
 [84 58 73 96 59]
 [31 25 67 25 91]
 [63 90 48 16 88]
 [35 19 47  6 27]]


In [4]:
first_row = matrix[0]
print("First Row:")
print(first_row)

First Row:
[70 95 93 41 68]


In [6]:
last_column = matrix[:, -1]
print("Last Column:")
print(last_column)

Last Column:
[68 59 91 88 27]


In [8]:
total_sum = matrix.sum()
print("Sum of All Elements:")
print(total_sum)

Sum of All Elements:
1415


In [12]:
matrix[matrix > 50] = 0
print("Modified Matrix:")
print(matrix)

Modified Matrix:
[[ 0  0  0 41  0]
 [ 0  0  0  0  0]
 [31 25  0 25  0]
 [ 0  0 48 16  0]
 [35 19 47  6 27]]
