In [2]:
matrix=[
    [2,3],
    [4,5]
] 

In [7]:
## support N_dim array
## Broadcasting
## MathmaticaL func
### integrate with other Lib

import numpy as np


In [84]:
#1D  vector
x=np.array([1,2,3])
print(x)
x.shape

[1 2 3]


(3,)

In [22]:
#2D
x=np.array([[1,2,3],[1,2,3],[4,5,6]])
print(x)
x.shape

[[1 2 3]
 [1 2 3]
 [4 5 6]]


(3, 3)

In [48]:
#3D
x=np.array([
       [
    [1,2,3],[1,2,3]
       ],
       [
     [1,2,3],[1,2,3]
       ]
 
            ])
print(x)
x.shape

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


(2, 2, 3)

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [66]:
np.random.rand(2,3)

array([[0.92332505, 0.80869767, 0.16137556],
       [0.06958022, 0.27119145, 0.07542868]])

In [92]:
x=np.random.randint(1,5,size=(3,3),dtype=np.uint8)
x

array([[3, 3, 1],
       [3, 4, 3],
       [2, 1, 2]], dtype=uint8)

In [94]:
x[1,1]

4

In [106]:
x[1][1]

4

In [108]:
x[1]

array([3, 4, 3], dtype=uint8)

In [110]:
x[1,:]

array([3, 4, 3], dtype=uint8)

In [148]:
sum=0
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        sum=x[i,j]+sum
sum

22

In [136]:
x.shape[0]

3

In [138]:
y=np.random.randint(1,5,size=(2,3),dtype=np.uint8)

In [140]:
y.shape[0]

2

In [142]:
y.shape[1]

3

In [156]:
sum=0
for row in x:
    for element in row:
        sum=x[i,j]+sum

In [154]:
sum

18

In [73]:
# Define two matrices x and y
x=np.random.randint(1,5,size=(3,3),dtype=np.uint8)
y=np.random.randint(1,5,size=(3,3),dtype=np.uint8)
print (x,
       y)

[[4 4 4]
 [4 3 4]
 [4 1 3]] [[1 3 3]
 [2 1 4]
 [4 1 4]]


In [75]:
# Method using nested loops
# Initialize an empty result matrix with the same dimensions
add =np.zeros((3,3))
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        add[i,j] =x[i,j]+y[i,j]
add        

array([[5., 7., 7.],
       [6., 4., 8.],
       [8., 2., 7.]])

In [77]:
# dot product
# Method using nested loops
# Initialize an empty result matrix with the same dimensions
dopro =np.zeros((3,3))
# Triple nested loops to calculate matrix multiplication
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        for k in range(x.shape[1]):
            dopro[i,j] +=x[i,k]*y[k,j]
dopro   

array([[28., 20., 44.],
       [26., 19., 40.],
       [18., 16., 28.]])

In [79]:
# Method using the @ operator
x@y

array([[28, 20, 44],
       [26, 19, 40],
       [18, 16, 28]], dtype=uint8)

In [81]:
# Method using np.dot
np.dot(x,y)

array([[28, 20, 44],
       [26, 19, 40],
       [18, 16, 28]], dtype=uint8)

In [87]:
# Add 10 to each element of the matrix
x+10


array([[14, 14, 14],
       [14, 13, 14],
       [14, 11, 13]], dtype=uint8)

In [106]:
#x.sum() sums all elements.
#x.sum(axis=0) sums elements column-wise.
#x.sum(axis=1) sums elements row-wise.
x.sum()

31

In [108]:
# x.sum(axis=0) sums elements column-wise.
# x.sum(axis=1) sums elements row-wise.
np.sum(x)

31

In [110]:
np.max(x)

4

In [112]:
np.min(x)

1

In [114]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.transpose(x)
x.T

array([[4, 4, 4],
       [4, 3, 1],
       [4, 4, 3]], dtype=uint8)

In [122]:
# Compute the determinant of x
np.linalg.det(x)


4.0

In [124]:
np.linalg.inv(x)

array([[ 1.25, -2.  ,  1.  ],
       [ 1.  , -1.  , -0.  ],
       [-2.  ,  3.  , -1.  ]])