In [235]:
matex=[[2,3],[4,5]]
matex

[[2, 3], [4, 5]]

In [237]:
##support in dimantion matrex
## pytin list is slower than numpy as it based on C
## nupay BROADCASTING add num to matrex
##maathmatical function
##integtrate with ather lib
import numpy


In [239]:
x=numpy.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [241]:
import numpy as np

In [243]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [245]:
## 2d dimentin 
y=np.array([[1,2,4],[4,5,5],[5,5,2]])
y
y.shape

(3, 3)

In [247]:
## 3d dimention 
y=np.array([
    [
        [1,2,4],[4,5,5],[5,5,2]
    ],   
    [
        [1,2,4],[4,5,5],[5,5,2]
    ],     
          ])
y
y.shape

(2, 3, 3)

In [249]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [251]:
np.random.rand(2,3)

array([[0.63491614, 0.27150989, 0.23971912],
       [0.28064213, 0.23430894, 0.33756159]])

In [253]:
m = np.random.randint(0, 10, size=(3,3))
m

array([[3, 3, 1],
       [0, 4, 7],
       [4, 0, 8]])

In [255]:
g=m[1,:]
print(g)
m[:,1]
print(g)
g=m[1:,1:]
print(g)

[0 4 7]
[0 4 7]
[[4 7]
 [0 8]]


In [257]:
g=m[1:,1:]
print(g)

[[4 7]
 [0 8]]


In [259]:
total_sum = 0

for i in range(m.shape[0]):
    for j in range(m.shape[0]):
        total_sum += m[i, j]

print(total_sum)

30


In [261]:
sum=0
for row in m:
    for cal in row:
        sum += cal

sum        

30

In [280]:
d = np.random.randint(0, 10, size=(3,3))
ss = np.random.randint(0, 10, size=(3,3))
print (d)
print (ss)

[[2 8 6]
 [2 8 1]
 [7 5 9]]
[[0 5 7]
 [7 9 0]
 [6 1 4]]


In [282]:
for i in range(m.shape[0]):
    for j in range(m.shape[0]):
        ss[i, j]=m[i, j]*d[i, j]

In [284]:
print (ss)

[[ 6 24  6]
 [ 0 32  7]
 [28  0 72]]


In [286]:
#dot product
for i in range(3):
    for j in range(3):
        for k in range(3):
            ss [i,j]+=m[i,k]*d[k,j]

In [288]:
print (ss)

[[ 25  77  36]
 [ 57  99  74]
 [ 92  72 168]]


In [290]:
ss=np.dot(m,d)

In [292]:
print (ss)

[[19 53 30]
 [57 67 67]
 [64 72 96]]
