In [6]:
matex=[[2,3],[4,5]]
matex

[[2, 3], [4, 5]]

In [8]:
##support in dimantion matrex
## pytin list is slower than numpy as it based on C
## nupay BROADCASTING add num to matrex
##maathmatical function
##integtrate with ather lib
import numpy


In [14]:
x=numpy.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [16]:
import numpy as np

In [20]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [88]:
## 2d dimentin 
y=np.array([[1,2,4],[4,5,5],[5,5,2]])
y
y.shape

(3, 3)

In [90]:
## 3d dimention 
y=np.array([
    [
        [1,2,4],[4,5,5],[5,5,2]
    ],   
    [
        [1,2,4],[4,5,5],[5,5,2]
    ],     
          ])
y
y.shape

(2, 3, 3)

In [92]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [94]:
np.random.rand(2,3)

array([[0.46727466, 0.62856303, 0.09943393],
       [0.21639598, 0.16122328, 0.92416171]])

In [101]:
m = np.random.randint(0, 10, size=(3,3))
m

array([[0, 8, 4],
       [3, 6, 9],
       [8, 5, 6]])

In [117]:
g=m[1,:]
print(g)
m[:,1]
print(g)
g=m[1:,1:]
print(g)

[3 6 9]
[3 6 9]
[[6 9]
 [5 6]]


In [115]:
g=m[1:,1:]
print(g)

[[6 9]
 [5 6]]


In [123]:
total_sum = 0

for i in range(m.shape[0]):
    for j in range(m.shape[0]):
        total_sum += m[i, j]

print(total_sum)

49


In [141]:
sum=0
for row in m:
    for cal in row:
        sum += cal

sum        

49

In [200]:
d = np.random.randint(0, 10, size=(3,3))
ss = np.random.randint(0, 10, size=(3,3))
print (d)
print (ss)

[[0 0 3]
 [8 5 8]
 [8 1 1]]
[[7 5 1]
 [1 3 6]
 [2 4 6]]


In [202]:
for i in range(m.shape[0]):
    for j in range(m.shape[0]):
        ss[i, j]=m[i, j]*d[i, j]

In [204]:
print (ss)

[[ 0  0 12]
 [24 30 72]
 [64  5  6]]


In [206]:
#dot product
for i in range(3):
    for j in range(3):
        for k in range(3):
            ss [i,j]+=m[i,k]*d[k,j]

In [214]:
print (ss)

[[ 96  44  68]
 [120  39  66]
 [ 88  31  70]]


In [210]:
ss=np.dot(m,d)

In [212]:
ss

array([[ 96,  44,  68],
       [120,  39,  66],
       [ 88,  31,  70]])